name: 3Dpicasso
favicon: null
layout_spectrum: 0.5952438288368285
typography_spectrum: 0.24948651622980833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.30982714612036943
  lightness: 0.023235939675942063
  saturation: 0.811737651238218
  rhythmicContrast: 0.6255885798018426
purpose: []
