name: 3Dpicasso
favicon: null
layout_spectrum: 0.5952438288368285
typography_spectrum: 0.24948651622980833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7b7c7e'
    - '#2a261b'
    - '#90211a'
    - '#d3cd38'
    - '#31b7d4'
  brandStrength: 0.30982714612036943
  lightness: 0.023235939675942063
  saturation: 0.811737651238218
  rhythmicContrast: 0.6255885798018426
purpose: []
